#########################################
#				FUNCTIONS: Start
#########################################
# Check if path is found then appends it to the path
# - use before as argument two to prepend it to the path
function add_to_path() {
	dir_test=$1
	position=${2:-after}
	if [[ -d "$dir_test" ]]; then
		if [[ "$position" == "before" ]]; then
			# echo \
			export PATH="$dir_test:$PATH"
		else
			# echo \
			export PATH="$PATH:$dir_test"
		fi
	fi
}

# Clean PATH in-place
function clean_path() {
	emulate -L zsh
	setopt extendedglob

	typeset -a newpath
	typeset -A seen

	local p
	for p in ${(s/:/)PATH}; do
		# skip empty, non-dirs, or already seen
		[[ -n "$p" && -d "$p" && -z "${seen[$p]}" ]] || continue
		newpath+="$p"
		seen[$p]=1
	done

	PATH="${(j/:/)newpath}"
}

# Check if software in path
# SETTINGS: LOG
# ':inane:function:software'
# - 'error' yes/no
# - 'success' yes/no
# usage: hasSoftware "fresh"
function hasSoftware() {
	if which $1 >/dev/null; then
		if zstyle -t ':inane:function:software' 'success'; then
			msg "Found Software: $Green$1"
		fi
		return 0
	else
		if zstyle -t ':inane:function:software' 'error'; then
			msg "Missing Software: $Red$1"
		fi
		return 1
	fi
}

# Add To Path And Clean
# the same as add_to_path but removes duplicates as it goes.
function addToPathAndClean() {
	add_to_path "$1" "${2:-after}"
	clean_path
}

################################################
########## initialise config environment
################################################
zstyle ':inane:function:*' 'error' yes
zstyle ':inane:function:*' 'success' yes
################################################
if [[ -f ~/.zsh.d/$OPT_SOURCE.env ]]; then
	source ~/.zsh.d/$OPT_SOURCE.env
fi
################################################


# Lines configured by zsh-newuser-install
setopt autocd extendedglob
unsetopt nomatch
bindkey -e

if hasSoftware "tabs"; then
	tabs -4
fi
setopt beep nomatch
# End of lines configured by zsh-newuser-install
# If you come from bash you might have to change your $PATH.
addToPathAndClean /usr/local/mysql-9.3.0-macos15-arm64/bin "before"
addToPathAndClean "$HOME/Applications/Visual Studio Code.app/Contents/Resources/app/bin" "before"
addToPathAndClean "$HOME/.composer/vendor/bin" "before"
addToPathAndClean /usr/local/bin "before"
addToPathAndClean "$HOME/.local/bin" "before"
addToPathAndClean "$HOME/bin" "before"
addToPathAndClean "$HOME/.cargo/bin"

################################################
########## initialise config variables
################################################
plugins=()
export STARSHIP_CONFIG=~/.config/starship/default.toml
################################################
if [[ -f ~/.zsh.d/$OPT_SOURCE.zsh ]]; then
	source ~/.zsh.d/$OPT_SOURCE.zsh
fi
################################################

# Prompt for spelling correction of commands.
#setopt CORRECT

# Customize spelling correction prompt.
SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
# Remove path separator from WORDCHARS.
WORDCHARS=${WORDCHARS//[\/]/}

# zsh-autosuggestions
# Customize the style that the suggestions are shown with.
# See https://github.com/zsh-users/zsh-autosuggestions/blob/master/README.md#suggestion-highlight-style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=10'

# zsh-syntax-highlighting
# Set what highlighters will be used.
# See https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters.md
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment one of the following lines to change the auto-update behaviour
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode auto # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13
zstyle ':omz:update' frequency 6

## config
zstyle ':inane:*' editor fresh

zstyle ':omz:plugins:eza' 'dirs-first' yes
zstyle ':omz:plugins:eza' 'icons' yes
zstyle ':omz:plugins:eza' 'size-prefix' si

zstyle :omz:plugins:iterm2 shell-integration yes

zstyle ':omz:plugins:alias-finder' autoload yes # disabled by default
zstyle ':omz:plugins:alias-finder' longer yes   # disabled by default
zstyle ':omz:plugins:alias-finder' exact yes    # disabled by default
zstyle ':omz:plugins:alias-finder' cheaper yes  # disabled by default

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colours in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

export MANPATH="/usr/share/man:/usr/local/share/man:/usr/X11/man:/Library/Apple/usr/share/man:$MANPATH"

if hasSoftware "brew"; then
	export MANPATH="$HOME/man:$(brew --prefix)/share/man:$MANPATH"
fi

# AUTOUPDATE
# manually call: upgrade_oh_my_zsh_custom
export UPDATE_ZSH_DAYS=5
ZSH_CUSTOM_AUTOUPDATE_QUIET=false
ZSH_CUSTOM_AUTOUPDATE_NUM_WORKERS=1

# INANE
if [[ -f "$HOME/.inane/init.zsh" ]]; then
	eval "$(cat $HOME/.inane/init.zsh)"
fi

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# zsh-syntax-highlighting
plugins+=($plugins aliases alias-finder copyfile copypath fzf git sudo z)
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
	export EDITOR=fresh
else
	export EDITOR=code
fi
export VISUAL="$EDITOR"

# Compilation flags
export ARCHFLAGS="-arch $(uname -m)"

if hasSoftware "brew"; then
	addToPathAndClean "$HOMEBREW_PREFIX/opt/sqlite/bin" "before"
	addToPathAndClean "$HOMEBREW_PREFIX/opt/ruby/bin" "before"
	addToPathAndClean "$HOMEBREW_PREFIX/bin" "before"
	addToPathAndClean "$HOMEBREW_PREFIX/sbin" "before"
fi

# INANE
# term app
# - Apple_Terminal
# - iTerm.app
# - ghostty
# - xterm-kitty
[[ ! -z $TERM_PROGRAM ]] && INANE_TERM_PROGRAM=$TERM_PROGRAM || INANE_TERM_PROGRAM=$TERM

INANE_SHELL_TYPE=0
# test interactive shell
if [[ -o interactive ]]; then
	INANE_SHELL_TYPE=1
	# test stdin is a terminal
	if [[ -t 0 ]]; then
		INANE_SHELL_TYPE=2
	fi
fi

# export DASHT_DOCSETS_DIR=/Users/philip/Library/Application\ Support/Dash/DocSets/

################################################
########## custom end includes
################################################
if [[ -f ~/.zsh.d/$OPT_SOURCE.zshrc ]]; then
	source ~/.zsh.d/$OPT_SOURCE.zshrc
fi
################################################

export PATH
